(()=>{
const V=window.APP_VERSION||'1.19.1',BUILD=window.APP_BUILD||'2026.09.25-62',KEY='dabistaFarmV1';
const $=s=>document.querySelector(s),esc=window.esc||((s)=>String(s??''));
const db=window.db;
if(!db||!Array.isArray(db.horses))return;
const css=`.quickmare{white-space:nowrap}.v15box{margin-top:12px;padding:11px;border:1px solid #dce2dd;border-radius:12px;background:#fafbf9}.v15box b{font-size:13px}.v15help{font-size:12px;color:#66736c;line-height:1.55}.v15ped{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:8px 0}.v15ped>div{background:#f6f7f4;border-radius:9px;padding:8px}.v15ped small{display:block;color:#66736c;margin-bottom:3px}.v15meter{display:flex;justify-content:space-between;gap:8px;background:#f6f7f4;border-radius:9px;padding:7px 9px;margin-top:8px;font-size:12px}.v15warn{background:#fff3cd!important;color:#6b5200!important}@media(max-width:520px){#horses .toolbar{flex-wrap:wrap}#horses .toolbar input{flex-basis:100%}.v15ped{grid-template-columns:1fr 1fr}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
window.APP_VERSION=V;window.APP_BUILD=BUILD;const ver=$('#ver');if(ver)ver.textContent=`v${V} / Build ${BUILD}`;
let changed=false;db.horses.forEach(h=>{if(!h.role){h.role=h.id==='inari-shuttle'?'stallion':h.sex==='牝'?'broodmare':'race';changed=true}['damSire','sireSire','sireDam','damDam','sireDamSire','damDamSire'].forEach(k=>{if(h[k]===undefined){h[k]='';changed=true}})});if(changed&&window.saveFarm)window.saveFarm();
const roleLabel=r=>({race:'競走馬',broodmare:'繁殖牝馬','sire-candidate':'種牡馬候補',stallion:'種牡馬'}[r]||'登録馬');
function progress(h){const a=[h.sire,h.sireDamSire,h.damSire,h.damDamSire];return{done:a.filter(Boolean).length,total:4,items:[['父',h.sire],['父母父',h.sireDamSire],['母父',h.damSire],['母母父',h.damDamSire]]}}
function addRoleAndPedigreeFields(){const form=$('#horseForm');if(!form||$('#role'))return;const name=$('#name');name.insertAdjacentHTML('beforebegin',`<div class="two"><div><label>登録区分</label><select id="role"><option value="race">競走馬</option><option value="broodmare">繁殖牝馬</option><option value="sire-candidate">種牡馬候補</option><option value="stallion">種牡馬</option></select></div><div><label>用途メモ</label><input id="roleMemo" placeholder="例：配合用・後継候補"></div></div>`);const parentRow=$('#sire').closest('.two');parentRow.insertAdjacentHTML('afterend',`<div class="v15box"><b>血統入力</b><div class="v15help">繁殖牝馬は、配合理論判定に使う「父・父母父・母父・母母父」を分かる範囲で登録してください。空欄でも保存できます。</div><div class="two"><div><label>母父</label><input id="damSire"></div><div><label>父父</label><input id="sireSire"></div></div><div class="two"><div><label>父母</label><input id="sireDam"></div><div><label>母母</label><input id="damDam"></div></div><div class="two"><div><label>父母父</label><input id="sireDamSire" placeholder="父の母の父"></div><div><label>母母父</label><input id="damDamSire" placeholder="母の母の父"></div></div></div>`);$('#role').addEventListener('change',()=>{if($('#role').value==='broodmare')$('#sex').value='牝'})}
function resetHorseForm(mode='race'){const f=$('#horseForm');f.reset();$('#editId').value='';$('#role').value=mode;$('#roleMemo').value='';$('#sex').value=mode==='broodmare'?'牝':'牡';f.querySelector('h2').textContent=mode==='broodmare'?'繁殖牝馬を登録':'馬を登録'}
function openMare(){resetHorseForm('broodmare');horseDlg.showModal()}
function fillHorse(h){resetHorseForm(h.role||h.sex==='牝'?'broodmare':'race');const map={editId:h.id,role:h.role||(h.sex==='牝'?'broodmare':'race'),roleMemo:h.roleMemo,name:h.name,sex:h.sex,generation:h.generation,sire:h.sire,dam:h.dam,damSire:h.damSire,sireSire:h.sireSire,sireDam:h.sireDam,damDam:h.damDam,sireDamSire:h.sireDamSire,damDamSire:h.damDamSire,minD:h.minD,maxD:h.maxD,record:h.record,guts:h.guts,stable:h.stable,starts:h.starts,g1:h.g1,note:h.note};Object.entries(map).forEach(([k,v])=>{const el=$('#'+k);if(el)el.value=v??''});$('#horseForm h2').textContent='馬を編集';horseDlg.showModal()}
function saveHorse(e){e.preventDefault();const id=$('#editId').value||crypto.randomUUID(),old=db.horses.find(x=>x.id===id)||{},h={...old,id,name:$('#name').value.trim(),sex:$('#sex').value,role:$('#role').value,roleMemo:$('#roleMemo').value.trim(),generation:$('#generation').value.trim(),sire:$('#sire').value.trim(),dam:$('#dam').value.trim(),damSire:$('#damSire').value.trim(),sireSire:$('#sireSire').value.trim(),sireDam:$('#sireDam').value.trim(),damDam:$('#damDam').value.trim(),sireDamSire:$('#sireDamSire').value.trim(),damDamSire:$('#damDamSire').value.trim(),minD:+$('#minD').value||'',maxD:+$('#maxD').value||'',record:$('#record').value,guts:$('#guts').value,stable:$('#stable').value,starts:$('#starts').value.trim(),g1:$('#g1').value.trim(),note:$('#note').value.trim()};if(h.role==='broodmare')h.sex='牝';const i=db.horses.findIndex(x=>x.id===id);i<0?db.horses.push(h):db.horses[i]=h;if(window.saveFarm)window.saveFarm();if(window.renderHorses)window.renderHorses();if(window.renderBreed)window.renderBreed();horseDlg.close()}
function decorateCards(){document.querySelectorAll('#horseList [data-id]').forEach(c=>{if(c.dataset.v15)return;c.dataset.v15='1';const h=db.horses.find(x=>x.id===c.dataset.id);if(!h)return;const head=c.querySelector('h2')?.parentElement;if(head){const role=document.createElement('span');role.className='badge '+(h.role==='broodmare'?'gold':'');role.textContent=roleLabel(h.role);head.appendChild(role)}if(h.role==='broodmare'){const p=progress(h),m=document.createElement('div');m.className='v15meter';m.innerHTML=`<span>配合理論用血統</span><b>${p.done}/4</b>`;const grid=c.querySelector('.grid');if(grid)grid.insertAdjacentElement('beforebegin',m)}})}
function installHorseUI(){addRoleAndPedigreeFields();const tb=$('#horses .toolbar'),photo=$('#photoBtn');if(tb&&!$('#addMareBtn')){const b=document.createElement('button');b.id='addMareBtn';b.className='primary quickmare';b.textContent='＋繁殖牝馬';b.onclick=openMare;tb.insertBefore(b,photo)}$('#addBtn').onclick=()=>{resetHorseForm('race');horseDlg.showModal()};$('#horseForm').onsubmit=saveHorse;$('#horseList').onclick=e=>{const c=e.target.closest('[data-id]');if(!c)return;const h=db.horses.find(x=>x.id===c.dataset.id);if(h)fillHorse(h)};const mo=new MutationObserver(decorateCards);mo.observe($('#horseList'),{childList:true,subtree:true});decorateCards()}
function addBreedHelp(){const sec=$('#breed');if(!sec||$('#v15MareHelp'))return;const first=sec.querySelector('.card');const card=document.createElement('div');card.className='card';card.id='v15MareHelp';card.innerHTML=`<h3 class="section-title">繁殖牝馬の登録</h3><p class="muted">「＋ 繁殖牝馬」から登録します。配合に使う場合は父・母に加え、分かる範囲で父母父・母父・母母父も登録してください。</p><button class="primary" id="breedAddMare">＋ 繁殖牝馬を登録</button>`;sec.insertBefore(card,first);$('#breedAddMare').onclick=openMare;const holder=document.createElement('div');holder.id='marePedigreeCard';first.insertAdjacentElement('afterend',holder)}
function breedHorseById(id){return window.getBreedHorseById?.(id)||db.horses.find(x=>x.id===id)||null}
function filterMares(){const sel=$('#breedMare');if(!sel)return;[...sel.options].slice(1).forEach(o=>{const h=breedHorseById(o.value);if(h&&h.role!=='broodmare')o.remove()})}
function renderMareCard(){filterMares();const sel=$('#breedMare'),box=$('#marePedigreeCard');if(!sel||!box)return;const h=breedHorseById(sel.value);if(!h){box.innerHTML='';return}if(h.transientBreedOnly){box.innerHTML=`<div class="card"><div class="row"><h3 class="section-title">${esc(h.name)} の血統</h3><span class="badge gold">15祖先内蔵</span></div><p class="muted">Switch版繁殖牝馬マスタの15祖先・面白／見事用系統を使って判定します。手入力は不要です。</p><div class="master-pedigree-note">セリ設計からの一時表示です。馬DB・バックアップJSONには保存されません。</div></div>`;return}const p=progress(h),missing=p.items.filter(x=>!x[1]).map(x=>x[0]);box.innerHTML=`<div class="card"><div class="row"><h3 class="section-title">${esc(h.name)} の血統登録</h3><span class="badge ${p.done===4?'gold':'v15warn'}">${p.done}/4</span></div><div class="v15ped">${p.items.map(x=>`<div><small>${x[0]}</small><b>${esc(x[1]||'未登録')}</b></div>`).join('')}</div><p class="muted">${p.done===4?'配合理論用4枠を登録済みです。次段階で大系統マスタと照合します。':'不足：'+missing.join('・')+'。この牝馬を編集して追加入力できます。'}</p>${h.transientBreedOnly?'<div class="master-pedigree-note">セリ設計からの一時表示です。馬DBには保存されません。</div>':'<button class="secondary" id="editMareFromBreed">この牝馬を編集</button>'}</div>`;if(!h.transientBreedOnly)$('#editMareFromBreed').onclick=()=>fillHorse(h)}
function installBreedUI(){addBreedHelp();const sel=$('#breedMare');if(sel){sel.addEventListener('change',renderMareCard);const mo=new MutationObserver(()=>{filterMares();renderMareCard()});mo.observe(sel,{childList:true});setTimeout(()=>{filterMares();renderMareCard()},100)}}
function downloadJSON(obj,name){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function newer(a,b){const A=String(a).split('.').map(Number),B=String(b).split('.').map(Number);for(let i=0;i<3;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return false}
let latest=null;async function checkUpdate(show=false){try{const u=new URL('version.json',location.href);u.searchParams.set('_',Date.now());const r=await fetch(u,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw Error('HTTP '+r.status);latest=await r.json();if(newer(latest.version,V)||latest.build!==BUILD){$('#updateText').textContent=`最新版 v${latest.version} / ${latest.build} があります`;$('#updatebar').classList.add('show')}else{$('#updatebar').classList.remove('show');if(show)alert(`最新版です\nv${V} / ${BUILD}`)}}catch(e){if(show)alert('更新確認に失敗しました。通信状態を確認してください。')}}
async function forceUpdate(){try{if('serviceWorker'in navigator){for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister()}if('caches'in window){for(const k of await caches.keys())await caches.delete(k)}}catch{}const u=new URL(location.href);u.searchParams.set('update',Date.now());location.replace(u.href)}
function installSupport(){const r=$('#refreshBtn'),a=$('#applyUpdate'),d=$('#diagBtn');if(r)r.onclick=()=>checkUpdate(true);if(a)a.onclick=forceUpdate;if(d)d.onclick=()=>downloadJSON({diagnostic:true,generatedAt:new Date().toISOString(),app:{version:V,build:BUILD,url:location.href,standalone:matchMedia('(display-mode: standalone)').matches||navigator.standalone===true},remoteVersion:latest,device:{userAgent:navigator.userAgent,language:navigator.language,online:navigator.onLine},storage:{horseCount:db.horses.length,broodmareCount:db.horses.filter(h=>h.role==='broodmare').length,raceCount:db.races?.length||0,pedigreeComplete:db.horses.filter(h=>h.role==='broodmare'&&progress(h).done===4).length,bytes:new Blob([JSON.stringify(db)]).size},errors:window.APP_ERRORS||[],data:db},`dabista-diagnostic-v${V}.json`)}
installHorseUI();installBreedUI();installSupport();
})();