(()=>{
const V=window.APP_VERSION||'1.19.1',BUILD=window.APP_BUILD||'2026.09.23-51';
const $=s=>document.querySelector(s),db=window.db,esc=window.esc||((s)=>String(s??''));
if(!db)return;
window.APP_VERSION=V;window.APP_BUILD=BUILD;
const ver=$('#ver');if(ver)ver.textContent=`v${V} / Build ${BUILD}`;

/* iOS: dialog外のページが一緒に動く問題を防ぐ */
const css=`body.dabista-modal-lock{position:fixed!important;left:0;right:0;width:100%;overflow:hidden!important}dialog{max-height:calc(100dvh - 18px)!important;overflow:hidden!important;margin:auto!important}dialog .form{max-height:calc(100dvh - 18px)!important;overflow-y:auto!important;-webkit-overflow-scrolling:touch;overscroll-behavior:contain;padding-bottom:calc(18px + env(safe-area-inset-bottom))}.auto-tools,.master-tools{margin-top:9px;padding:10px;border-radius:10px;background:#f6f7f4}.master-tools{background:#eef4ef;border:1px solid #d8e5dc}.auto-row{display:flex;gap:7px;align-items:end}.auto-row>div{flex:1}.auto-status,.master-status{font-size:11px;color:#66736c;line-height:1.5;margin-top:6px}.auto-filled{background:#f3ead0!important;border-color:#d7be74!important}.small-btn{border:1px solid #dce2dd;background:#fff;border-radius:9px;padding:9px 10px;white-space:nowrap}.source-chip{display:inline-block;font-size:10px;border-radius:999px;padding:3px 6px;background:#e8efe9;margin-left:4px}.master-results{display:grid;gap:5px;margin-top:6px;max-height:220px;overflow:auto}.master-result{width:100%;text-align:left;border:1px solid #dce2dd;background:#fff;border-radius:9px;padding:8px}.master-result b{display:block;font-size:13px}.master-result small{color:#66736c}.mare-base{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:7px}.mare-base>div{background:#fff;border-radius:8px;padding:6px;text-align:center}.mare-base b{display:block;font-size:14px}.mare-base small{font-size:10px;color:#66736c}.master-count{margin-top:8px;font-size:11px;color:#52645a}.stallion-hit{font-size:11px;padding:7px 9px;margin-top:6px;border-radius:8px;background:#edf3ee;color:#405349}.default-mare-line{font-size:11px;color:#66736c;margin:8px 0 0}.default-mare-line b{color:#17221d}.master-summary{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.master-summary>div{background:#f6f7f4;border-radius:9px;padding:9px}.master-summary b{font-size:17px;display:block}@media(max-width:430px){.auto-row{align-items:stretch;flex-direction:column}.small-btn{width:100%}.mare-base{grid-template-columns:repeat(2,1fr)}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
let lockedY=0;
function lockBody(){if(document.body.classList.contains('dabista-modal-lock'))return;lockedY=window.scrollY||0;document.body.style.top=`-${lockedY}px`;document.body.classList.add('dabista-modal-lock')}
function unlockBody(){if(document.querySelector('dialog[open]'))return;document.body.classList.remove('dabista-modal-lock');document.body.style.top='';window.scrollTo(0,lockedY)}
if(!window.__dabistaDialogPatch){window.__dabistaDialogPatch=true;const nativeShow=HTMLDialogElement.prototype.showModal;HTMLDialogElement.prototype.showModal=function(){lockBody();return nativeShow.call(this)};document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',unlockBody));document.addEventListener('touchmove',e=>{const open=document.querySelector('dialog[open]');if(open&&!e.target.closest('dialog[open]'))e.preventDefault()},{passive:false})}

let pedigreeMaster=[],defaultMares=[],stallionMaster=[];
let selectedDefaultMare=null;
let masterStatus={pedigree:{status:'loading',count:0},broodmares:{status:'loading',count:0},stallions:{status:'loading',count:0}};
const norm=s=>String(s||'').trim().replace(/[\s・･]/g,'').toLowerCase();
function localEntries(){return db.horses.map(h=>({name:h.name,sire:h.sire||'',dam:h.dam||'',damSire:h.damSire||'',source:'牧場DB'}))}
function findHorse(name){const n=norm(name);if(!n)return null;return localEntries().find(x=>norm(x.name)===n)||pedigreeMaster.find(x=>norm(x.name)===n)||null}
function findDefaultMare(name){const n=norm(name);return n?defaultMares.find(x=>norm(x.name)===n)||null:null}
function findStallion(name){const n=norm(name);return n?stallionMaster.find(x=>norm(x.name)===n)||null:null}
window.findPedigreeHorse=findHorse;window.findDefaultBroodmare=findDefaultMare;window.findDefaultStallion=findStallion;
function markFill(id,val){const el=$(id);if(!el||!val||el.value.trim())return false;el.value=val;el.classList.add('auto-filled');setTimeout(()=>el.classList.remove('auto-filled'),1600);return true}
function fillPedigree(show=true){let fills=[],sources=[];const sire=findHorse($('#sire')?.value),dam=findHorse($('#dam')?.value);
  if(sire){if(markFill('#sireSire',sire.sire))fills.push('父父');if(markFill('#sireDam',sire.dam))fills.push('父母');if(markFill('#sireDamSire',sire.damSire))fills.push('父母父');sources.push(`父:${sire.source||'血統マスタ'}`)}
  if(dam){if(markFill('#damSire',dam.sire))fills.push('母父');if(markFill('#damDam',dam.dam))fills.push('母母');if(markFill('#damDamSire',dam.damSire))fills.push('母母父');sources.push(`母:${dam.source||'血統マスタ'}`)}
  updateAutoStatus(fills,sources,show);updateSireStatus();return fills.length
}
window.fillPedigreeFromMaster=fillPedigree;
function updateAutoStatus(fills=[],sources=[],show=false){const el=$('#autoStatus');if(!el)return;const sireKnown=!!findHorse($('#sire')?.value),damKnown=!!findHorse($('#dam')?.value);if(fills.length)el.innerHTML=`${fills.join('・')}を補完しました。${sources.map(x=>`<span class="source-chip">${esc(x)}</span>`).join('')}`;else if(sireKnown||damKnown)el.textContent='補完できる血統項目は入力済みです。';else el.textContent='父または母を候補から選ぶと、確認済みの血統情報を自動で引き継ぎます。';if(show&&fills.length===0&&!sireKnown&&!damKnown)alert('一致する父・母の詳細血統がまだありません。名称・基礎データはマスタにあっても、父母情報は未確認の場合があります。')}
function refreshDatalist(){let dl=$('#pedigreeNames');if(!dl){dl=document.createElement('datalist');dl.id='pedigreeNames';document.body.appendChild(dl)}const names=[...new Set([...localEntries().map(x=>x.name),...pedigreeMaster.map(x=>x.name),...stallionMaster.map(x=>x.name),...defaultMares.map(x=>x.name)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja'));dl.innerHTML=names.map(n=>`<option value="${esc(n)}"></option>`).join('');['sire','dam','damSire','sireSire','sireDam','damDam','sireDamSire','damDamSire'].forEach(id=>{const el=$('#'+id);if(el)el.setAttribute('list','pedigreeNames')});const pick=$('#registeredDamPick');if(pick){const keep=pick.value;pick.innerHTML='<option value="">登録済みの母馬から選択</option>'+db.horses.filter(h=>h.sex==='牝').map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('');pick.value=[...pick.options].some(o=>o.value===keep)?keep:''}updateMasterCount()}
function updateSireStatus(){const box=$('#sireMasterStatus');if(!box)return;const x=findStallion($('#sire')?.value);if(!x){box.textContent='';box.style.display='none';return}box.style.display='block';box.innerHTML=`デフォルト種牡馬：${x.minD}–${x.maxD}m / 実績${x.record}・底力${x.guts}・安定${x.stable} / NSP ${x.nsp}・NST ${x.nst}・NPW ${x.npw}`}
function updateMasterCount(){const el=$('#masterCount');if(!el)return;el.textContent=`内蔵マスタ：国内種牡馬 ${stallionMaster.length||'…'}頭 / デフォルト繁殖牝馬 ${defaultMares.length||'…'}頭 / 詳細血統 ${pedigreeMaster.length||'…'}頭`}

function mareStatsHtml(m){if(!m)return'';const val=(v,unknown='未判明')=>(v===0&&m.ver==='1.1')?unknown:v;return`<div class="mare-base"><div><b>${val(m.sp)}</b><small>SP</small></div><div><b>${val(m.st)}</b><small>ST</small></div><div><b>${val(m.pw)}</b><small>PW</small></div><div><b>${m.dirt||'?'}</b><small>ダート</small></div><div><b>${m.nsp}</b><small>NSP</small></div><div><b>${m.nst}</b><small>NST</small></div><div><b>${m.npw}</b><small>NPW</small></div><div><b>${m.price.toLocaleString()}</b><small>価格(万)</small></div></div>`}
function updateSelectedMareBox(){const el=$('#selectedMareMaster');if(!el)return;if(!selectedDefaultMare){el.innerHTML='';el.style.display='none';return}el.style.display='block';el.innerHTML=`<div class="master-status">ゲーム内デフォルト繁殖牝馬 <b>${esc(selectedDefaultMare.name)}</b>（Ver ${esc(selectedDefaultMare.ver)}）</div>${mareStatsHtml(selectedDefaultMare)}`}
function renderMareResults(q=''){const box=$('#defaultMareResults');if(!box)return;const n=norm(q);let a=defaultMares.filter(m=>!n||norm(m.name).includes(n));if(!n)a=a.sort((x,y)=>y.price-x.price);a=a.slice(0,10);box.innerHTML=a.map(m=>`<button type="button" class="master-result" data-master-mare="${esc(m.name)}"><b>${esc(m.name)}</b><small>SP ${m.sp||'?'} / ST ${m.st||'?'} / PW ${m.pw||'?'}　${m.price.toLocaleString()}万　Ver ${esc(m.ver)}</small></button>`).join('')+(defaultMares.length&&!a.length?'<div class="master-status">一致する繁殖牝馬がありません。</div>':'');box.querySelectorAll('[data-master-mare]').forEach(b=>b.onclick=()=>applyDefaultMare(findDefaultMare(b.dataset.masterMare)))}
function applyDefaultMare(m){if(!m)return;const current=$('#name')?.value.trim();if(current&&norm(current)!==norm(m.name)&&!confirm(`入力中の「${current}」を「${m.name}」に置き換えますか？`))return;selectedDefaultMare=m;if($('#name'))$('#name').value=m.name;if($('#role'))$('#role').value='broodmare';if($('#sex'))$('#sex').value='牝';if($('#generation')&&!$('#generation').value.trim())$('#generation').value='ゲーム内デフォルト繁殖牝馬';const known=findHorse(m.name);if(known){markFill('#sire',known.sire);markFill('#dam',known.dam);markFill('#damSire',known.damSire)}fillPedigree(false);updateSelectedMareBox();const q=$('#defaultMareQuery');if(q)q.value=m.name;const res=$('#defaultMareResults');if(res)res.innerHTML=''}
function clearDefaultMare(){selectedDefaultMare=null;const q=$('#defaultMareQuery');if(q)q.value='';const res=$('#defaultMareResults');if(res)res.innerHTML='';updateSelectedMareBox()}

function installAutoUI(){const box=document.querySelector('.v15box');if(!box||$('#autoFillPedigree'))return;box.insertAdjacentHTML('afterbegin',`<div class="master-tools"><b>ゲーム内マスタから入力</b><div class="master-status">既存の繁殖牝馬を選べば、名前や基礎能力を0から入力する必要はありません。</div><input id="defaultMareQuery" autocomplete="off" placeholder="繁殖牝馬名を検索（例：ミココロノママニ）" style="width:100%;margin-top:7px"><div id="defaultMareResults" class="master-results"></div><div id="selectedMareMaster" style="display:none"></div><div id="masterCount" class="master-count"></div></div><div class="auto-tools"><div class="auto-row"><div><label>登録済み母馬を使う</label><select id="registeredDamPick"><option value="">登録済みの母馬から選択</option></select></div><button type="button" class="small-btn" id="autoFillPedigree">血統を自動補完</button></div><div id="autoStatus" class="auto-status">父または母を候補から選ぶと、確認済み血統を自動で引き継ぎます。</div><div id="sireMasterStatus" class="stallion-hit" style="display:none"></div></div>`);refreshDatalist();$('#autoFillPedigree').onclick=()=>fillPedigree(true);$('#registeredDamPick').onchange=e=>{const h=db.horses.find(x=>x.id===e.target.value);if(!h)return;$('#dam').value=h.name;fillPedigree(false)};$('#defaultMareQuery').oninput=e=>renderMareResults(e.target.value);$('#defaultMareQuery').onfocus=e=>renderMareResults(e.target.value);document.addEventListener('click',e=>{if(!e.target.closest('.master-tools')){const r=$('#defaultMareResults');if(r)r.innerHTML=''}});['sire','dam'].forEach(id=>{const el=$('#'+id);if(el){el.addEventListener('change',()=>fillPedigree(false));el.addEventListener('blur',()=>fillPedigree(false));el.addEventListener('input',()=>{if(id==='sire')updateSireStatus()})}});$('#name')?.addEventListener('input',()=>{if(selectedDefaultMare&&norm($('#name').value)!==norm(selectedDefaultMare.name)){selectedDefaultMare=null;updateSelectedMareBox()}})}

function resetCompactHorseSections(){
 document.querySelectorAll('#horseForm .horse-compact-details').forEach(d=>d.open=false);
}
function syncCompactHorseRole(){
 const brood=$('#role')?.value==='broodmare',master=$('#horseForm .master-tools');
 if(master)master.hidden=!brood;
}
function installCompactHorseForm(){
 const form=$('#horseForm');if(!form||$('#horseFormStickyHead'))return;
 if(!$('#horseCompactStyle')){const s=document.createElement('style');s.id='horseCompactStyle';s.textContent=`
  #horseDlg .form{padding-top:0!important}
  .horse-form-sticky-head{position:sticky;top:0;z-index:8;display:flex;align-items:center;justify-content:space-between;gap:10px;margin:0 -1px 12px;padding:12px 0 10px;background:rgba(255,255,255,.97);border-bottom:1px solid #e0e9e4;backdrop-filter:blur(9px)}
  .horse-form-sticky-head h2{margin:0;font-size:20px}.horse-form-sticky-actions{display:flex;gap:6px;flex:0 0 auto}.horse-form-sticky-actions button{padding:8px 10px}
  #horseForm>.actions.horse-bottom-actions{display:none!important}
  .horse-compact-details{margin-top:10px;border:1px solid #dce6e0;border-radius:12px;background:#fbfcfb;overflow:hidden}
  .horse-compact-details>summary{cursor:pointer;list-style:none;padding:11px 12px;font-size:12px;font-weight:900;color:#315544}.horse-compact-details>summary::-webkit-details-marker{display:none}
  .horse-compact-details>summary:after{content:'＋';float:right;color:#6a7d73}.horse-compact-details[open]>summary:after{content:'−'}
  .horse-compact-body{padding:0 10px 10px}.horse-compact-body>.two,.horse-compact-body>.three{margin-top:8px}
  #horseForm>.master-tools{margin:8px 0 10px!important}
  #horseForm .v15box{padding:0!important;border:0!important;background:transparent!important;margin-top:8px!important}
  #horseForm .v15box>.horse-compact-details{margin-top:0}
  @media(max-width:520px){.horse-form-sticky-head{margin-left:-2px;margin-right:-2px}.horse-form-sticky-head h2{font-size:18px}.horse-form-sticky-actions button{font-size:11px;padding:7px 9px}}
 `;document.head.appendChild(s)}
 const h2=form.querySelector('h2'),head=document.createElement('div');head.id='horseFormStickyHead';head.className='horse-form-sticky-head';
 h2.parentNode.insertBefore(head,h2);head.appendChild(h2);
 const actions=document.createElement('div');actions.className='horse-form-sticky-actions';actions.innerHTML='<button type="button" class="secondary" id="horseTopCancel">取消</button><button type="button" class="primary" id="horseTopSave">保存</button>';head.appendChild(actions);
 $('#horseTopCancel').onclick=()=>horseDlg.close();$('#horseTopSave').onclick=()=>form.requestSubmit();
 const bottom=form.querySelector(':scope>.actions');if(bottom)bottom.classList.add('horse-bottom-actions');
 const master=form.querySelector('.master-tools'),name=$('#name');if(master&&name)name.insertAdjacentElement('afterend',master);
 const box=form.querySelector('.v15box');
 if(box&&!box.querySelector('.horse-pedigree-details')){
   const details=document.createElement('details');details.className='horse-compact-details horse-pedigree-details';
   details.innerHTML='<summary>血統を詳しく入力・自動補完</summary><div class="horse-compact-body"></div>';
   const body=details.querySelector('.horse-compact-body');
   [...box.children].filter(x=>x!==master).forEach(x=>body.appendChild(x));box.appendChild(details);
 }
 if(!form.querySelector('.horse-performance-details')){
   const details=document.createElement('details');details.className='horse-compact-details horse-performance-details';
   details.innerHTML='<summary>距離・実績・戦績・メモ</summary><div class="horse-compact-body"></div>';
   const body=details.querySelector('.horse-compact-body'),nodes=[];
   for(const id of ['minD','record','starts']){
     const el=$('#'+id),g=el?.closest('.two,.three');if(g&&!nodes.includes(g))nodes.push(g);
   }
   const note=$('#note'),noteLabel=note?.previousElementSibling;
   nodes.forEach(x=>body.appendChild(x));if(noteLabel?.tagName==='LABEL')body.appendChild(noteLabel);if(note)body.appendChild(note);
   const before=bottom||null;form.insertBefore(details,before);
 }
 $('#role')?.addEventListener('change',syncCompactHorseRole);syncCompactHorseRole();resetCompactHorseSections();
}
function resetForm(mode='race'){const f=$('#horseForm');if(!f)return;f.reset();resetCompactHorseSections();if($('#editId'))$('#editId').value='';if($('#role'))$('#role').value=mode;if($('#roleMemo'))$('#roleMemo').value='';if($('#sex'))$('#sex').value=mode==='broodmare'?'牝':'牡';f.querySelector('h2').textContent=mode==='broodmare'?'繁殖牝馬を登録':'馬を登録';clearDefaultMare();refreshDatalist();updateAutoStatus();updateSireStatus();syncCompactHorseRole()}
function openExisting(h){const f=$('#horseForm');if(!f)return;f.reset();resetCompactHorseSections();const mode=h.role||(h.sex==='牝'?'broodmare':'race');if($('#role'))$('#role').value=mode;if($('#roleMemo'))$('#roleMemo').value=h.roleMemo||'';const map={editId:h.id,name:h.name,sex:h.sex,generation:h.generation,sire:h.sire,dam:h.dam,damSire:h.damSire,sireSire:h.sireSire,sireDam:h.sireDam,damDam:h.damDam,sireDamSire:h.sireDamSire,damDamSire:h.damDamSire,minD:h.minD,maxD:h.maxD,record:h.record,guts:h.guts,stable:h.stable,starts:h.starts,g1:h.g1,note:h.note};Object.entries(map).forEach(([k,v])=>{const el=$('#'+k);if(el)el.value=v??''});selectedDefaultMare=h.masterRef?.type==='default-broodmare'?(findDefaultMare(h.masterRef.name)||h.mareStats&&{name:h.masterRef.name,...h.mareStats,ver:h.masterRef.ver||''}):null;f.querySelector('h2').textContent=mode==='broodmare'?'繁殖牝馬を編集':'馬を編集';refreshDatalist();updateSelectedMareBox();updateAutoStatus();updateSireStatus();syncCompactHorseRole();horseDlg.showModal()}
function saveHorse(e){e.preventDefault();fillPedigree(false);const id=$('#editId').value||crypto.randomUUID(),old=db.horses.find(x=>x.id===id)||{},h={...old,id,name:$('#name').value.trim(),sex:$('#sex').value,role:$('#role')?.value||(($('#sex').value==='牝')?'broodmare':'race'),roleMemo:$('#roleMemo')?.value.trim()||'',generation:$('#generation').value.trim(),sire:$('#sire').value.trim(),dam:$('#dam').value.trim(),damSire:$('#damSire')?.value.trim()||'',sireSire:$('#sireSire')?.value.trim()||'',sireDam:$('#sireDam')?.value.trim()||'',damDam:$('#damDam')?.value.trim()||'',sireDamSire:$('#sireDamSire')?.value.trim()||'',damDamSire:$('#damDamSire')?.value.trim()||'',minD:+$('#minD').value||'',maxD:+$('#maxD').value||'',record:$('#record').value,guts:$('#guts').value,stable:$('#stable').value,starts:$('#starts').value.trim(),g1:$('#g1').value.trim(),note:$('#note').value.trim()};if(h.role==='broodmare')h.sex='牝';if(selectedDefaultMare&&norm(selectedDefaultMare.name)===norm(h.name)){h.masterRef={type:'default-broodmare',name:selectedDefaultMare.name,ver:selectedDefaultMare.ver};h.mareStats={price:selectedDefaultMare.price,sp:selectedDefaultMare.sp,st:selectedDefaultMare.st,pw:selectedDefaultMare.pw,dirt:selectedDefaultMare.dirt,nsp:selectedDefaultMare.nsp,nst:selectedDefaultMare.nst,npw:selectedDefaultMare.npw,nstBook:selectedDefaultMare.nstBook}}else if(h.masterRef?.type==='default-broodmare'&&norm(h.masterRef.name)!==norm(h.name)){delete h.masterRef;delete h.mareStats}const i=db.horses.findIndex(x=>x.id===id);i<0?db.horses.push(h):db.horses[i]=h;window.saveFarm?.();window.renderHorses?.();window.renderBreed?.();refreshDatalist();horseDlg.close()}
function overrideEditing(){const list=$('#horseList');if(list)list.onclick=e=>{const c=e.target.closest('[data-id]');if(!c)return;const h=db.horses.find(x=>x.id===c.dataset.id);if(h)openExisting(h)};const form=$('#horseForm');if(form)form.onsubmit=saveHorse;const add=$('#addBtn');if(add)add.onclick=()=>{resetForm('race');horseDlg.showModal()};const addMare=$('#addMareBtn');if(addMare)addMare.onclick=()=>{resetForm('broodmare');horseDlg.showModal()};const breedAdd=$('#breedAddMare');if(breedAdd)breedAdd.onclick=()=>{resetForm('broodmare');horseDlg.showModal()}}
function decorateHorseCards(){document.querySelectorAll('#horseList [data-id]').forEach(c=>{let old=c.querySelector('.default-mare-line');if(old)old.remove();const h=db.horses.find(x=>x.id===c.dataset.id);if(!h?.mareStats)return;const line=document.createElement('div');line.className='default-mare-line';line.innerHTML=`<b>デフォルト牝馬</b>　SP ${h.mareStats.sp||'?'} / ST ${h.mareStats.st||'?'} / PW ${h.mareStats.pw||'?'} / NSP ${h.mareStats.nsp} / NST ${h.mareStats.nst}`;const grid=c.querySelector('.grid');if(grid)grid.insertAdjacentElement('beforebegin',line)})}
function installCardObserver(){const list=$('#horseList');if(!list)return;new MutationObserver(decorateHorseCards).observe(list,{childList:true,subtree:true});decorateHorseCards()}
function installMasterSummary(){const sec=$('#breed');if(!sec||$('#defaultMasterSummary'))return;const first=sec.querySelector('.card');const card=document.createElement('div');card.className='card';card.id='defaultMasterSummary';card.innerHTML=`<h3 class="section-title">ゲーム内デフォルトマスタ</h3><div class="master-summary"><div><b id="stallionCount">…</b><small>国内種牡馬</small></div><div><b id="mareCount">…</b><small>繁殖牝馬</small></div></div><p class="muted">マスタは牧場所有馬とは別管理です。必要な繁殖牝馬だけを読み込むため、馬DBが大量の既存馬で埋まりません。</p>`;sec.insertBefore(card,first)}
function updateSummary(){if($('#stallionCount'))$('#stallionCount').textContent=stallionMaster.length||'…';if($('#mareCount'))$('#mareCount').textContent=defaultMares.length||'…';updateMasterCount()}

async function loadJSON(path){const u=new URL(path,location.href);u.searchParams.set('_',BUILD);const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`${path} HTTP ${r.status}`);return r.json()}
async function loadMasters(){const jobs=[
  loadJSON('data/pedigree-master.json').then(d=>{pedigreeMaster=(d.horses||[]).map(x=>({...x,source:'血統マスタ'}));masterStatus.pedigree={status:'ok',count:pedigreeMaster.length}}).catch(e=>{masterStatus.pedigree={status:'failed',error:String(e),count:0}}),
  loadJSON('data/default-broodmares.json').then(d=>{defaultMares=d.broodmares||[];masterStatus.broodmares={status:'ok',count:defaultMares.length,syncedAt:d.syncedAt||null}}).catch(e=>{masterStatus.broodmares={status:'failed',error:String(e),count:0}}),
  loadJSON('data/stallions.json').then(d=>{stallionMaster=d.stallions||[];masterStatus.stallions={status:'ok',count:stallionMaster.length,syncedAt:d.syncedAt||null}}).catch(e=>{masterStatus.stallions={status:'failed',error:String(e),count:0}})
];await Promise.all(jobs);window.DABISTA_MASTER_STATUS=masterStatus;window.DEFAULT_BROODMARES=defaultMares;window.DEFAULT_STALLIONS=stallionMaster;refreshDatalist();updateAutoStatus();updateSireStatus();updateSummary();if(selectedDefaultMare){const fresh=findDefaultMare(selectedDefaultMare.name);if(fresh)selectedDefaultMare=fresh;updateSelectedMareBox()}const bad=Object.entries(masterStatus).filter(([,v])=>v.status==='failed');if(bad.length)window.APP_ERRORS?.push({at:new Date().toISOString(),message:'master-load: '+bad.map(([k,v])=>`${k}:${v.error}`).join(' | ')})}

function downloadJSON(obj,name){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function newer(a,b){const A=String(a).split('.').map(Number),B=String(b).split('.').map(Number);for(let i=0;i<3;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return false}
let remote=null;async function checkUpdate(show=false){try{const u=new URL('version.json',location.href);u.searchParams.set('_',Date.now());const r=await fetch(u,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw Error('HTTP '+r.status);remote=await r.json();if(newer(remote.version,V)||remote.build!==BUILD){$('#updateText').textContent=`最新版 v${remote.version} / ${remote.build} があります`;$('#updatebar').classList.add('show')}else{$('#updatebar').classList.remove('show');if(show)alert(`最新版です\nv${V} / ${BUILD}`)}}catch(e){if(show)alert('更新確認に失敗しました。通信状態を確認してください。')}}
async function forceUpdate(){try{if('serviceWorker'in navigator){for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister()}if('caches'in window){for(const k of await caches.keys())await caches.delete(k)}}catch{}const u=new URL(location.href);u.searchParams.set('update',Date.now());location.replace(u.href)}
function installSupport(){if($('#refreshBtn'))$('#refreshBtn').onclick=()=>checkUpdate(true);if($('#applyUpdate'))$('#applyUpdate').onclick=forceUpdate;if($('#diagBtn'))$('#diagBtn').onclick=()=>downloadJSON({diagnostic:true,generatedAt:new Date().toISOString(),app:{version:V,build:BUILD,url:location.href,standalone:matchMedia('(display-mode: standalone)').matches||navigator.standalone===true},remoteVersion:remote,masters:masterStatus,modal:{bodyLocked:document.body.classList.contains('dabista-modal-lock'),openDialogs:document.querySelectorAll('dialog[open]').length},device:{userAgent:navigator.userAgent,language:navigator.language,online:navigator.onLine},storage:{horseCount:db.horses.length,broodmareCount:db.horses.filter(h=>h.role==='broodmare').length,defaultMareImportedCount:db.horses.filter(h=>h.masterRef?.type==='default-broodmare').length,raceCount:db.races?.length||0,bytes:new Blob([JSON.stringify(db)]).size},errors:window.APP_ERRORS||[],data:db},`dabista-diagnostic-v${V}.json`)}

installAutoUI();installCompactHorseForm();overrideEditing();installCardObserver();installMasterSummary();installSupport();loadMasters();
})();