(()=>{
const V='1.6.0',BUILD='2026.09.15-22';
const $=s=>document.querySelector(s),db=window.db,esc=window.esc||((s)=>String(s??''));
if(!db)return;
window.APP_VERSION=V;window.APP_BUILD=BUILD;
const ver=$('#ver');if(ver)ver.textContent=`v${V} / Build ${BUILD}`;

/* iOS: dialog外のページが一緒に動く問題を防ぐ */
const css=`body.dabista-modal-lock{position:fixed!important;left:0;right:0;width:100%;overflow:hidden!important}dialog{max-height:calc(100dvh - 18px)!important;overflow:hidden!important;margin:auto!important}dialog .form{max-height:calc(100dvh - 18px)!important;overflow-y:auto!important;-webkit-overflow-scrolling:touch;overscroll-behavior:contain;padding-bottom:calc(18px + env(safe-area-inset-bottom))}.auto-tools{margin-top:9px;padding:9px;border-radius:10px;background:#f6f7f4}.auto-row{display:flex;gap:7px;align-items:end}.auto-row>div{flex:1}.auto-status{font-size:11px;color:#66736c;line-height:1.45;margin-top:6px}.auto-filled{background:#f3ead0!important;border-color:#d7be74!important}.small-btn{border:1px solid #dce2dd;background:#fff;border-radius:9px;padding:9px 10px;white-space:nowrap}.source-chip{display:inline-block;font-size:10px;border-radius:999px;padding:3px 6px;background:#e8efe9;margin-left:4px}@media(max-width:430px){.auto-row{align-items:stretch;flex-direction:column}.small-btn{width:100%}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
let lockedY=0;
function lockBody(){if(document.body.classList.contains('dabista-modal-lock'))return;lockedY=window.scrollY||0;document.body.style.top=`-${lockedY}px`;document.body.classList.add('dabista-modal-lock')}
function unlockBody(){if(document.querySelector('dialog[open]'))return;document.body.classList.remove('dabista-modal-lock');document.body.style.top='';window.scrollTo(0,lockedY)}
if(!window.__dabistaDialogPatch){window.__dabistaDialogPatch=true;const nativeShow=HTMLDialogElement.prototype.showModal;HTMLDialogElement.prototype.showModal=function(){lockBody();return nativeShow.call(this)};document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',unlockBody));document.addEventListener('touchmove',e=>{const open=document.querySelector('dialog[open]');if(open&&!e.target.closest('dialog[open]'))e.preventDefault()},{passive:false})}

let master=[];let masterStatus={status:'loading',count:0};
const norm=s=>String(s||'').trim().replace(/[\s・･]/g,'').toLowerCase();
function localEntries(){return db.horses.map(h=>({name:h.name,sire:h.sire||'',dam:h.dam||'',damSire:h.damSire||'',source:'牧場DB'}))}
function findHorse(name){const n=norm(name);if(!n)return null;return localEntries().find(x=>norm(x.name)===n)||master.find(x=>norm(x.name)===n)||null}
function markFill(id,val){const el=$(id);if(!el||!val||el.value.trim())return false;el.value=val;el.classList.add('auto-filled');setTimeout(()=>el.classList.remove('auto-filled'),1600);return true}
function fillPedigree(show=true){let fills=[],sources=[];const sire=findHorse($('#sire')?.value),dam=findHorse($('#dam')?.value);
  if(sire){if(markFill('#sireSire',sire.sire))fills.push('父父');if(markFill('#sireDam',sire.dam))fills.push('父母');if(markFill('#sireDamSire',sire.damSire))fills.push('父母父');sources.push(`父:${sire.source||'血統マスタ'}`)}
  if(dam){if(markFill('#damSire',dam.sire))fills.push('母父');if(markFill('#damDam',dam.dam))fills.push('母母');if(markFill('#damDamSire',dam.damSire))fills.push('母母父');sources.push(`母:${dam.source||'血統マスタ'}`)}
  updateAutoStatus(fills,sources,show);return fills.length
}
function updateAutoStatus(fills=[],sources=[],show=false){const el=$('#autoStatus');if(!el)return;const sireKnown=!!findHorse($('#sire')?.value),damKnown=!!findHorse($('#dam')?.value);if(fills.length)el.innerHTML=`${fills.join('・')}を補完しました。${sources.map(x=>`<span class="source-chip">${esc(x)}</span>`).join('')}`;else if(sireKnown||damKnown)el.textContent='補完できる項目は入力済みです。';else el.textContent='父または母を候補から選ぶと、登録済み血統を自動で引き継ぎます。';if(show&&fills.length===0&&!sireKnown&&!damKnown)alert('一致する父・母がまだ血統マスタにありません。分かる項目だけ入力して保存できます。')}
function refreshDatalist(){let dl=$('#pedigreeNames');if(!dl){dl=document.createElement('datalist');dl.id='pedigreeNames';document.body.appendChild(dl)}const names=[...new Set([...localEntries().map(x=>x.name),...master.map(x=>x.name)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja'));dl.innerHTML=names.map(n=>`<option value="${esc(n)}"></option>`).join('');['sire','dam','damSire','sireSire','sireDam','damDam','sireDamSire','damDamSire'].forEach(id=>{const el=$('#'+id);if(el)el.setAttribute('list','pedigreeNames')});const pick=$('#registeredDamPick');if(pick){const keep=pick.value;pick.innerHTML='<option value="">登録済みの母馬から選択</option>'+db.horses.filter(h=>h.sex==='牝').map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('');pick.value=[...pick.options].some(o=>o.value===keep)?keep:''}}
function installAutoUI(){const box=document.querySelector('.v15box');if(!box||$('#autoFillPedigree'))return;box.insertAdjacentHTML('afterbegin',`<div class="auto-tools"><div class="auto-row"><div><label>登録済み母馬を使う</label><select id="registeredDamPick"><option value="">登録済みの母馬から選択</option></select></div><button type="button" class="small-btn" id="autoFillPedigree">血統を自動補完</button></div><div id="autoStatus" class="auto-status">父または母を候補から選ぶと、登録済み血統を自動で引き継ぎます。</div></div>`);refreshDatalist();$('#autoFillPedigree').onclick=()=>fillPedigree(true);$('#registeredDamPick').onchange=e=>{const h=db.horses.find(x=>x.id===e.target.value);if(!h)return;$('#dam').value=h.name;fillPedigree(false)};['sire','dam'].forEach(id=>{const el=$('#'+id);if(el){el.addEventListener('change',()=>fillPedigree(false));el.addEventListener('blur',()=>fillPedigree(false))}})}

function openExisting(h){const f=$('#horseForm');if(!f)return;f.reset();const mode=h.role||(h.sex==='牝'?'broodmare':'race');if($('#role'))$('#role').value=mode;if($('#roleMemo'))$('#roleMemo').value=h.roleMemo||'';const map={editId:h.id,name:h.name,sex:h.sex,generation:h.generation,sire:h.sire,dam:h.dam,damSire:h.damSire,sireSire:h.sireSire,sireDam:h.sireDam,damDam:h.damDam,sireDamSire:h.sireDamSire,damDamSire:h.damDamSire,minD:h.minD,maxD:h.maxD,record:h.record,guts:h.guts,stable:h.stable,starts:h.starts,g1:h.g1,note:h.note};Object.entries(map).forEach(([k,v])=>{const el=$('#'+k);if(el)el.value=v??''});f.querySelector('h2').textContent=mode==='broodmare'?'繁殖牝馬を編集':'馬を編集';refreshDatalist();updateAutoStatus();horseDlg.showModal()}
function overrideEditing(){const list=$('#horseList');if(list)list.onclick=e=>{const c=e.target.closest('[data-id]');if(!c)return;const h=db.horses.find(x=>x.id===c.dataset.id);if(h)openExisting(h)};const form=$('#horseForm');if(form)form.onsubmit=e=>{e.preventDefault();fillPedigree(false);const id=$('#editId').value||crypto.randomUUID(),old=db.horses.find(x=>x.id===id)||{},h={...old,id,name:$('#name').value.trim(),sex:$('#sex').value,role:$('#role')?.value||(($('#sex').value==='牝')?'broodmare':'race'),roleMemo:$('#roleMemo')?.value.trim()||'',generation:$('#generation').value.trim(),sire:$('#sire').value.trim(),dam:$('#dam').value.trim(),damSire:$('#damSire')?.value.trim()||'',sireSire:$('#sireSire')?.value.trim()||'',sireDam:$('#sireDam')?.value.trim()||'',damDam:$('#damDam')?.value.trim()||'',sireDamSire:$('#sireDamSire')?.value.trim()||'',damDamSire:$('#damDamSire')?.value.trim()||'',minD:+$('#minD').value||'',maxD:+$('#maxD').value||'',record:$('#record').value,guts:$('#guts').value,stable:$('#stable').value,starts:$('#starts').value.trim(),g1:$('#g1').value.trim(),note:$('#note').value.trim()};if(h.role==='broodmare')h.sex='牝';const i=db.horses.findIndex(x=>x.id===id);i<0?db.horses.push(h):db.horses[i]=h;window.saveFarm?.();window.renderHorses?.();window.renderBreed?.();refreshDatalist();horseDlg.close()}}

async function loadMaster(){try{const u=new URL('data/pedigree-master.json',location.href);u.searchParams.set('_',BUILD);const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();master=(d.horses||[]).map(x=>({...x,source:'血統マスタ'}));masterStatus={status:'ok',count:master.length};refreshDatalist();updateAutoStatus()}catch(e){masterStatus={status:'failed',error:String(e),count:0};window.APP_ERRORS?.push({at:new Date().toISOString(),message:'pedigree-master: '+String(e)})}}

function downloadJSON(obj,name){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function newer(a,b){const A=String(a).split('.').map(Number),B=String(b).split('.').map(Number);for(let i=0;i<3;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return false}
let remote=null;async function checkUpdate(show=false){try{const u=new URL('version.json',location.href);u.searchParams.set('_',Date.now());const r=await fetch(u,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw Error('HTTP '+r.status);remote=await r.json();if(newer(remote.version,V)||remote.build!==BUILD){$('#updateText').textContent=`最新版 v${remote.version} / ${remote.build} があります`;$('#updatebar').classList.add('show')}else{$('#updatebar').classList.remove('show');if(show)alert(`最新版です\nv${V} / ${BUILD}`)}}catch(e){if(show)alert('更新確認に失敗しました。通信状態を確認してください。')}}
async function forceUpdate(){try{if('serviceWorker'in navigator){for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister()}if('caches'in window){for(const k of await caches.keys())await caches.delete(k)}}catch{}const u=new URL(location.href);u.searchParams.set('update',Date.now());location.replace(u.href)}
function installSupport(){if($('#refreshBtn'))$('#refreshBtn').onclick=()=>checkUpdate(true);if($('#applyUpdate'))$('#applyUpdate').onclick=forceUpdate;if($('#diagBtn'))$('#diagBtn').onclick=()=>downloadJSON({diagnostic:true,generatedAt:new Date().toISOString(),app:{version:V,build:BUILD,url:location.href,standalone:matchMedia('(display-mode: standalone)').matches||navigator.standalone===true},remoteVersion:remote,pedigreeMaster:masterStatus,modal:{bodyLocked:document.body.classList.contains('dabista-modal-lock'),openDialogs:document.querySelectorAll('dialog[open]').length},device:{userAgent:navigator.userAgent,language:navigator.language,online:navigator.onLine},storage:{horseCount:db.horses.length,broodmareCount:db.horses.filter(h=>h.role==='broodmare').length,raceCount:db.races?.length||0,bytes:new Blob([JSON.stringify(db)]).size},errors:window.APP_ERRORS||[],data:db},`dabista-diagnostic-v${V}.json`);setTimeout(()=>checkUpdate(false),500);setTimeout(()=>checkUpdate(false),1500)}
installAutoUI();overrideEditing();installSupport();loadMaster();
})();