(()=>{
const V='1.10.0',BUILD='2026.09.15-26',db=window.db,$=s=>document.querySelector(s),norm=s=>String(s||'').normalize('NFKC').trim().replace(/[\s・･]/g,'').toLowerCase();if(!db)return;window.APP_VERSION=V;window.APP_BUILD=BUILD;const ve=$('#ver');if(ve)ve.textContent=`v${V} / Build ${BUILD}`;
const idx=[7,9,11,13],sort=a=>[...(a||[])].sort().join('|');
function buildSystemMap(){const T=window.DABISTA_THEORY_MASTER;if(!T)return null;const sets=new Map();[...(T.stallions||[]),...(T.broodmares||[])].forEach(h=>{if(!h.ancestor?.length||h.omoshiroSystems?.length!==4)return;idx.forEach((p,k)=>{const n=norm(h.ancestor[p]),c=h.omoshiroSystems[k];if(!n||!c)return;if(!sets.has(n))sets.set(n,new Set());sets.get(n).add(c)})});const out=new Map();sets.forEach((s,k)=>{if(s.size===1)out.set(k,[...s][0])});return out}
function deriveMare(h,map){if(!h||!map||!Array.isArray(h.ancestor15)||h.ancestor15.length!==15)return null;const names=idx.map(i=>h.ancestor15[i]),codes=names.map(n=>map.get(norm(n)));if(codes.some(x=>!x))return null;return{names,codes}}
function stallion(n){return window.DABISTA_THEORY_MASTER?.stallions?.find(x=>norm(x.name)===norm(n))||null}
function cardName(c){return c.querySelector('b')?.textContent.replace(/^\s*\d+\.\s*/,'').trim()||''}
function apply(){const map=buildSystemMap(),h=db.horses.find(x=>x.id===$('#breedMare')?.value),d=deriveMare(h,map),filter=$('#theoryFilter');document.querySelectorAll('.v20-theory').forEach(x=>x.remove());if(!h||!d)return;if(filter)filter.disabled=false;h.omoshiroSystems=d.codes;h.theorySource='derived-system-map';try{localStorage.setItem('dabistaFarmV1',JSON.stringify(db))}catch{}
 const st=$('#theoryStatus');if(st)st.innerHTML=`<b>${h.name}</b>：自家製血統の15祖先から面白用4系統を確定（${d.codes.join('・')}）。面白・見事・完璧を候補種牡馬ごとに判定します。`;
 const f=filter?.value||'all';document.querySelectorAll('#breedCandidates>.card').forEach(c=>{c.classList.remove('theory-hidden');const s=stallion(cardName(c));if(!s)return;const so=s.omoshiroSystems||[],sm=s.migotoSystems||[],unique=new Set([...d.codes,...so]).size,interesting=so.length===4&&unique>=7,magnificent=sm.length===4&&sort(d.codes)===sort(sm),perfect=interesting&&magnificent;const x=document.createElement('div');x.className='v20-theory';x.style.cssText='font-size:11px;line-height:1.5;margin-top:6px';x.innerHTML=`<div class="theory-chips">${perfect?'<span class="theory-chip perfect">完璧（面白＋見事）</span>':`${interesting?'<span class="theory-chip">面白</span>':''}${magnificent?'<span class="theory-chip migoto">見事</span>':''}`}<span class="theory-chip system">8系統中 ${unique}種類</span></div><div class="pair-theory-note">自家製牝馬 ${d.codes.join('・')} / 種牡馬・面白 ${so.join('・')||'未判定'} / 種牡馬・見事 ${sm.join('・')||'未判定'}</div>`;c.appendChild(x);const ok=f==='all'||(f==='any'&&(interesting||magnificent))||(f==='interesting'&&interesting)||(f==='magnificent'&&magnificent)||(f==='perfect'&&perfect);if(!ok)c.classList.add('theory-hidden')})}
let busy=false;function run(){if(busy)return;busy=true;try{apply()}finally{busy=false}}$('#breedMare')?.addEventListener('change',()=>setTimeout(run,80));$('#theoryFilter')?.addEventListener('change',()=>setTimeout(run,20));$('#stallionSearch')?.addEventListener('input',()=>setTimeout(run,80));const t=$('#breedCandidates');if(t)new MutationObserver(()=>queueMicrotask(run)).observe(t,{childList:true});setTimeout(run,1600);setTimeout(run,2800);
function newer(a,b){const A=String(a).split('.').map(Number),B=String(b).split('.').map(Number);for(let i=0;i<3;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return false}
async function check(show=false){try{const u=new URL('version.json',location.href);u.searchParams.set('_',Date.now());const r=await fetch(u,{cache:'no-store'}),v=await r.json();if(newer(v.version,V)||v.build!==BUILD){$('#updateText').textContent=`最新版 v${v.version} / ${v.build} があります`;$('#updatebar').classList.add('show')}else{$('#updatebar').classList.remove('show');if(show)alert(`最新版です\nv${V} / ${BUILD}`)}}catch{if(show)alert('更新確認に失敗しました。')}}
setTimeout(()=>{if($('#refreshBtn'))$('#refreshBtn').onclick=()=>check(true);check(false)},3100);
})();