(()=>{
const V='1.11.0',BUILD='2026.09.16-27',db=window.db,$=s=>document.querySelector(s),norm=s=>String(s||'').normalize('NFKC').trim().replace(/[\s・･]/g,'').toLowerCase();if(!db)return;window.APP_VERSION=V;window.APP_BUILD=BUILD;const ve=$('#ver');if(ve)ve.textContent=`v${V} / Build ${BUILD}`;
let pairs=[];const T=()=>window.DABISTA_THEORY_MASTER;const depth=i=>i<1?2:i<3?3:i<7?4:5;const master=n=>T()?.stallions?.find(x=>norm(x.name)===norm(n))||T()?.broodmares?.find(x=>norm(x.name)===norm(n))||null;const horse=n=>db.horses.find(x=>norm(x.name)===norm(n))||null;
function anc(h){if(!h)return null;if(h.ancestor15?.length===15)return h.ancestor15;const m=master(h.masterRef?.name||h.name);return m?.ancestor?.length===15?m.ancestor:null}
function cardName(c){return c.querySelector('b')?.textContent.replace(/^\s*\d+\.\s*/,'').trim()||''}
function nodesSire(s){return [{name:s.name,gen:1},...(s.ancestor||[]).map((name,i)=>({name,gen:depth(i)}))]}
function nodesMare(m){return (anc(m)||[]).map((name,i)=>({name,gen:depth(i)}))}
function crosses(m,s){const A=nodesSire(s),B=nodesMare(m),out=[];for(const a of A)for(const b of B)if(a.name&&b.name&&norm(a.name)===norm(b.name))out.push({name:a.name,sireGen:a.gen,mareGen:b.gen});const seen=new Set();return out.filter(x=>{const k=norm(x.name)+'|'+x.sireGen+'|'+x.mareGen;if(seen.has(k))return false;seen.add(k);return true})}
function danger(xs){const one=xs.find(x=>x.sireGen===1),two=xs.find(x=>x.sireGen===2&&x.mareGen===2);return{exact:!!(one||two),reason:one?`${one.name} ${one.sireGen}×${one.mareGen}`:two?`${two.name} 2×2`:'',sevenCandidate:xs.length>=7}}
function elaborate(m,s){if(!pairs.length)return[];const A=nodesSire(s).filter(x=>x.gen<=4),B=nodesMare(m).filter(x=>x.gen<=4),set=new Set(pairs.map(p=>norm(p.a)+'|'+norm(p.b))),out=[];for(const a of A)for(const b of B)if(a.name&&b.name&&set.has(norm(a.name)+'|'+norm(b.name)))out.push(`${a.name} × ${b.name}`);return[...new Set(out)]}
function controls(){if($('#v21Filter'))return;const box=$('.theory-tools');if(!box)return;const w=document.createElement('div');w.style.marginTop='8px';w.innerHTML='<label>公式配合理論・追加フィルター</label><select id="v21Filter"><option value="all">すべて</option><option value="elaborate">凝った配合</option><option value="cross">クロスあり</option><option value="safe">危険条件を除外</option></select><div style="font-size:10px;line-height:1.45;margin-top:5px;color:#66736c">面白・見事・完璧・凝った・危険条件は公式ルール判定。能力順位は「牧場内参考判定（非公式）」です。</div>';box.appendChild(w);$('#v21Filter').onchange=()=>setTimeout(run,0)}
function run(){controls();const m=db.horses.find(x=>x.id===$('#breedMare')?.value),f=$('#v21Filter')?.value||'all';document.querySelectorAll('#breedCandidates>.card').forEach(c=>{c.querySelectorAll('.v21-rule').forEach(x=>x.remove());c.classList.remove('v21-hidden');if(!m)return;const s=master(cardName(c));if(!s)return;const xs=crosses(m,s),d=danger(xs),e=elaborate(m,s);const box=document.createElement('div');box.className='v21-rule';box.style.cssText='font-size:11px;line-height:1.55;margin-top:7px;padding:7px 9px;border-radius:8px;background:#eef3ef;color:#405048';let chips='';if(e.length&&!d.exact)chips+='<span class="theory-chip perfect">凝った</span>';if(d.exact)chips+='<span class="theory-chip" style="background:#f5dddd;color:#7b2f2f">危険な配合</span>';else if(d.sevenCandidate)chips+='<span class="theory-chip" style="background:#f7ead7;color:#76521f">7本以上候補・要精査</span>';if(xs.length)chips+=`<span class="theory-chip system">共通祖先 ${xs.length}件</span>`;box.innerHTML=`<div class="theory-chips">${chips||'<span class="theory-chip system">追加理論なし</span>'}</div>${e.length?`<div>凝ったペア：${e.slice(0,4).join(' / ')}${e.length>4?' ほか':''}</div>`:''}${d.exact?`<div><b>危険条件：</b>${d.reason}。危険な配合では凝った配合は無効。</div>`:''}${xs.length?`<div>クロス：${xs.slice(0,7).map(x=>`${x.name} ${x.sireGen}×${x.mareGen}`).join(' / ')}${xs.length>7?' ほか':''}</div>`:''}${d.sevenCandidate&&!d.exact?'<div>※7本以上条件は、祖先内包クロスの除外前件数です。誤判定防止のため「候補」と表示します。</div>':''}`;c.appendChild(box);const ok=f==='all'||(f==='elaborate'&&e.length&&!d.exact)||(f==='cross'&&xs.length)||(f==='safe'&&!d.exact&&!d.sevenCandidate);if(!ok)c.classList.add('v21-hidden')})}
const style=document.createElement('style');style.textContent='.v21-hidden{display:none!important}';document.head.appendChild(style);
async function load(){try{const u=new URL('data/kotta-pairs.json',location.href);u.searchParams.set('_',BUILD);const r=await fetch(u,{cache:'no-store'});if(r.ok){const j=await r.json();pairs=j.pairs||[];window.DABISTA_KOTTA_STATUS={status:'ok',count:pairs.length}}else throw Error('HTTP '+r.status)}catch(e){window.DABISTA_KOTTA_STATUS={status:'failed',error:String(e)}}run()}
$('#breedMare')?.addEventListener('change',()=>setTimeout(run,100));$('#stallionSearch')?.addEventListener('input',()=>setTimeout(run,100));const target=$('#breedCandidates');if(target)new MutationObserver(()=>queueMicrotask(run)).observe(target,{childList:true});setTimeout(load,1700);setTimeout(run,3000);
function newer(a,b){const A=String(a).split('.').map(Number),B=String(b).split('.').map(Number);for(let i=0;i<3;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return false}async function check(show=false){try{const u=new URL('version.json',location.href);u.searchParams.set('_',Date.now());const r=await fetch(u,{cache:'no-store'}),v=await r.json();if(newer(v.version,V)||v.build!==BUILD){$('#updateText').textContent=`最新版 v${v.version} / ${v.build} があります`;$('#updatebar').classList.add('show')}else{$('#updatebar').classList.remove('show');if(show)alert(`最新版です\nv${V} / ${BUILD}`)}}catch{if(show)alert('更新確認に失敗しました。')}}setTimeout(()=>{if($('#refreshBtn'))$('#refreshBtn').onclick=()=>check(true);check(false)},3300);
})();