(()=>{
const V=window.APP_VERSION||'1.19.1',BUILD=window.APP_BUILD||'2026.09.24-55',db=window.db,$=s=>document.querySelector(s),norm=s=>String(s||'').normalize('NFKC').trim().replace(/[\s・･]/g,'').toLowerCase();if(!db)return;window.APP_VERSION=V;window.APP_BUILD=BUILD;const ve=$('#ver');if(ve)ve.textContent=`v${V} / Build ${BUILD}`;
const KNOWN={
 'イナリシャトル':{screenType:'pedigree-cross',sire:'バゴ',dam:'イナリワルツ',damSire:'ワイルドラッシュ',ancestor15:['バゴ','Nashwan','ワイルドラッシュ','Blushing Groom','Nureyev','Wild Again','マンハッタンカフェ','Red God','Bustino','Northern Dancer','Mr. Prospector','Icecapade','Plugged Nickle','サンデーサイレンス','Storm Cat'],crosses:[{name:'Nearctic',sireGen:5,mareGen:5},{name:'Halo',sireGen:5,mareGen:5}],source:'image-confirmed-2026-09-16'}
};
function save(){localStorage.setItem('dabistaFarmV1',JSON.stringify(db));window.db=db;window.renderHorses?.();window.renderBreed?.()}
function mergeHorse(h,d){const changes=[],conflicts=[];for(const k of ['sire','dam','damSire']){if(!d[k])continue;if(!h[k]){h[k]=d[k];changes.push(k)}else if(norm(h[k])!==norm(d[k]))conflicts.push({field:k,current:h[k],incoming:d[k]})}if(d.ancestor15?.length===15){if(!h.ancestor15?.length){h.ancestor15=[...d.ancestor15];changes.push('15祖先')}else if(JSON.stringify(h.ancestor15)!==JSON.stringify(d.ancestor15))conflicts.push({field:'15祖先',current:'登録済み',incoming:'画像情報'})}h.confirmedCrosses=h.confirmedCrosses||[];for(const c of d.crosses||[]){if(!h.confirmedCrosses.some(x=>norm(x.name)===norm(c.name)&&x.sireGen===c.sireGen&&x.mareGen===c.mareGen)){h.confirmedCrosses.push({...c,source:d.source});changes.push(`${c.name} ${c.sireGen}×${c.mareGen}`)}}h.imageEvidence=h.imageEvidence||[];if(!h.imageEvidence.some(x=>x.source===d.source))h.imageEvidence.push({source:d.source,screenType:d.screenType,addedAt:new Date().toISOString()});return{changes,conflicts}}
function applyKnown(name){const d=KNOWN[name],h=db.horses.find(x=>norm(x.name)===norm(name));if(!d||!h)return null;const r=mergeHorse(h,d);if(r.changes.length)save();return{horse:h,...r}}
function migrate(){const r=applyKnown('イナリシャトル');if(r?.changes.length)console.info('v1.12 image evidence migrated',r.changes)}
function ensureDialog(){if($('#imageMergeDlg'))return;const d=document.createElement('dialog');d.id='imageMergeDlg';d.innerHTML='<form method="dialog" class="form"><h2>画像から既存馬へ追記</h2><p class="muted">画像そのものは端末内で選択します。現在は画面種別と既存情報を照合し、確定済み画像データを安全に統合します。入力済みの異なる値は自動上書きしません。</p><label>追記先</label><select id="imageHorse"></select><div id="imageMergeInfo" class="notice"></div><div class="actions"><button class="secondary" value="cancel">閉じる</button><button type="button" class="primary" id="imageApply">確定情報を追記</button></div></form>';document.body.appendChild(d);$('#imageApply').onclick=()=>{const h=db.horses.find(x=>x.id===$('#imageHorse').value),data=h&&KNOWN[h.name];if(!data){$('#imageMergeInfo').textContent='この馬について、アプリ内で確定照合できる画像情報はまだありません。';return}const r=mergeHorse(h,data);if(r.changes.length)save();$('#imageMergeInfo').innerHTML=`追記：${r.changes.join(' / ')||'追加なし'}${r.conflicts.length?`<br>上書き保留：${r.conflicts.map(x=>x.field).join(' / ')}`:''}`}}
function openMerge(files){ensureDialog();$('#imageHorse').innerHTML=db.horses.map(h=>`<option value="${h.id}" ${norm(h.name)===norm('イナリシャトル')?'selected':''}>${window.esc?window.esc(h.name):h.name}</option>`).join('');$('#imageMergeInfo').textContent=`${files?.length||0}枚を選択。既存馬を選び、確定済みの画像情報を追記できます。`;$('#imageMergeDlg').showModal()}
function installPhoto(){const p=$('#photo'),b=$('#photoBtn');if(!p||!b)return;b.textContent='画像から追記';p.onchange=e=>openMerge(e.target.files)}
function decorate(){document.querySelectorAll('#horseList .horse').forEach(c=>{const id=c.dataset.id,h=db.horses.find(x=>x.id===id);if(!h?.confirmedCrosses?.length||c.querySelector('.v22-evidence'))return;const x=document.createElement('p');x.className='muted v22-evidence';x.innerHTML=`画像確認クロス：<b>${h.confirmedCrosses.map(z=>`${z.name} ${z.sireGen}×${z.mareGen}`).join(' / ')}</b>`;c.appendChild(x)})}
const oldRender=window.renderHorses;if(oldRender)window.renderHorses=()=>{oldRender();decorate()};
setTimeout(()=>{migrate();installPhoto();window.renderHorses?.();decorate()},800);
})();