(()=>{
const V=window.APP_VERSION||'1.19.1',BUILD=window.APP_BUILD||'2026.09.25-67',db=window.db,$=s=>document.querySelector(s);
if(!db)return;window.APP_VERSION=V;window.APP_BUILD=BUILD;const ver=$('#ver');if(ver)ver.textContent=`v${V} / Build ${BUILD}`;
const esc=window.esc||((s)=>String(s??''));let engine=null,stallions=[],research=null;
const master=name=>engine?.master(name)||null;
const breedHorseById=id=>window.getBreedHorseById?.(id)||db.horses.find(x=>x.id===id)||null;
const horseRec=h=>engine?.resolveHorse(h)||null;
const horseAnc=h=>horseRec(h)?.ancestor||null;
const calcAncestors=(a,b)=>engine?.calcNitro(a,b)||null;
const deriveChild=(sireName,sa,ma)=>engine?.deriveChildAncestor(sireName,sa,ma)||null;
function resolveSire(value){
 if(!value)return null;
 if(value.startsWith('db:')){const h=db.horses.find(x=>x.id===value.slice(3)),r=horseRec(h);if(!h||!r?.ancestor)return null;return{name:h.name,ancestor:r.ancestor,stats:{record:h.record||'-',guts:h.guts||'-',stable:h.stable||'-',minD:h.minD||'',maxD:h.maxD||'',source:'牧場DB'}}}
 const name=value.startsWith('m:')?value.slice(2):value,m=master(name),s=engine?.stallionStats(name);if(!m?.ancestor?.length)return null;
 return{name:m.name,ancestor:m.ancestor,stats:s?{record:s.record,guts:s.guts,stable:s.stable,minD:s.minD,maxD:s.maxD,source:'Switch版マスタ'}:{record:'-',guts:'-',stable:'-',minD:'',maxD:'',source:'血統マスタ'}}
}
function allSires(){const a=stallions.filter(s=>master(s.name)?.ancestor?.length===15).map(s=>({value:'m:'+s.name,name:s.name}));for(const h of db.horses.filter(h=>(h.role==='stallion'||h.role==='sire-candidate')&&horseAnc(h)))a.push({value:'db:'+h.id,name:h.name+'（自家製）'});return a}
function sireOptions(selected='',blank=true){return(blank?'<option value="">種牡馬を選択</option>':'')+allSires().map(x=>`<option value="${esc(x.value)}" ${x.value===selected?'selected':''}>${esc(x.name)}</option>`).join('')}
function sourceMares(){const names=new Set(research?.starters||[]),out=[];for(const n of names){const m=master(n);if(m?.ancestor?.length===15)out.push({value:'m:'+n,name:n,ancestor:m.ancestor})}for(const h of db.horses.filter(h=>h.role==='broodmare'||h.sex==='牝')){const a=horseAnc(h);if(a)out.push({value:'db:'+h.id,name:h.name+'（牧場）',ancestor:a})}return out}
function resolveMare(value){if(value?.startsWith('db:')){const h=db.horses.find(x=>x.id===value.slice(3)),r=horseRec(h);return h&&r?.ancestor?{name:h.name,ancestor:r.ancestor}:null}const name=value?.startsWith('m:')?value.slice(2):value,m=master(name);return m?.ancestor?.length===15?{name:m.name,ancestor:m.ancestor}:null}
function routeDefault(start,goal){return research?.routes?.find(r=>engine.core.key(r.startMare)===engine.core.key(start)&&r.goal===goal)?.firstSire||research?.routes?.find(r=>engine.core.key(r.startMare)===engine.core.key(start))?.firstSire||''}
function addStyles(){if($('#v25style'))return;const s=document.createElement('style');s.id='v25style';s.textContent=`.nitro-exact{margin-top:7px;padding:7px 9px;border-radius:9px;background:#edf3ee;font-size:11px;line-height:1.5;color:#405048}.nitro-exact b{color:#173f2e}.nitro-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:7px}.nitro-grid>div{background:#fff;border-radius:8px;padding:7px;text-align:center}.nitro-grid b{display:block;font-size:17px}.nitro-grid small{font-size:10px;color:#66736c}.nitro-stage{padding:10px;border:1px solid #dce2dd;border-radius:11px;margin-top:8px;background:#fafbf9}.nitro-stage label{display:block;font-size:12px;color:#66736c;margin-bottom:4px}.nitro-stage select{width:100%}.nitro-stage .unknown{font-size:10px;color:#6b5200;background:#fff3cd;padding:5px 7px;border-radius:7px;margin-top:6px}.v25-hidden{display:none!important}`;document.head.appendChild(s)}
function installFilter(){if(window.DABISTA_BREED_PAIR_INDEX)return;const tools=$('.theory-tools');if(!tools||$('#v25NitroFilter'))return;const d=document.createElement('div');d.style.marginTop='8px';d.innerHTML='<label>最終締めニトロ・フィルター</label><select id="v25NitroFilter"><option value="all">指定なし</option><option value="sp15">SP 15以上</option><option value="sp18">SP 18以上</option><option value="st5">ST 5以上</option><option value="bal">SP 15以上 ＋ ST 5以上</option></select><div style="font-size:10px;color:#66736c;margin-top:4px">共通配合エンジンで15祖先を統合し、同じ祖先は1頭として計算します。</div>';tools.appendChild(d);$('#v25NitroFilter').onchange=()=>decorateBreed()}
function candidateName(c){return c.dataset.sireName||c.querySelector('b')?.textContent.replace(/^\s*\d+\.\s*/,'').trim()||''}
function decorateBreed(){if(window.DABISTA_BREED_PAIR_INDEX)return;if(!engine||decorateBreed.busy)return;decorateBreed.busy=true;try{installFilter();const h=breedHorseById($('#breedMare')?.value),ma=horseAnc(h),filter=$('#v25NitroFilter')?.value||'all';document.querySelectorAll('#breedCandidates>.card').forEach(c=>{let box=c.querySelector('.nitro-exact');c.classList.remove('v25-hidden');if(!ma){if(box)box.remove();return}const sm=master(candidateName(c));if(!sm?.ancestor?.length){if(box)box.remove();return}const n=calcAncestors(sm.ancestor,ma);if(!n)return;const key=`${n.sp}|${n.st}|${n.pw}|${n.factorCount}`;if(!box){box=document.createElement('div');box.className='nitro-exact';c.appendChild(box)}if(box.dataset.nitroKey!==key){box.dataset.nitroKey=key;box.innerHTML=`<b>七光り（重複除外）</b>　SP <b>${n.sp}</b> / ST <b>${n.st}</b> / PW <b>${n.pw}</b><br><span>有効因子祖先 ${n.factorCount}種類。途中世代の親ニトロ単純加算ではなく、この配合の15祖先から再計算。</span>`}const ok=filter==='all'||(filter==='sp15'&&n.sp>=15)||(filter==='sp18'&&n.sp>=18)||(filter==='st5'&&n.st>=5)||(filter==='bal'&&n.sp>=15&&n.st>=5);if(!ok)c.classList.add('v25-hidden')})}finally{decorateBreed.busy=false}}
function stageHtml(num,sire,calc){if(!sire)return`<div id="nitroResult${num}" class="notice">種牡馬を選択すると、${num}代目配合のニトロを計算します。</div>`;const d=sire.stats||{},range=d.minD&&d.maxD?`${d.minD}–${d.maxD}m`:'距離未登録';return`<div id="nitroResult${num}" class="nitro-exact"><b>${num}代目：${esc(sire.name)}</b><div class="nitro-grid"><div><b>${calc.sp}</b><small>SPニトロ</small></div><div><b>${calc.st}</b><small>STニトロ</small></div><div><b>${calc.pw}</b><small>PWニトロ</small></div></div><div style="margin-top:6px">${range} / 実績${esc(d.record)}・底力${esc(d.guts)}・安定${esc(d.stable)} / 有効因子${calc.factorCount}種類</div><div class="unknown">この数値は血統上の上限側指標です。自家製牝馬自身の繁殖SP/ST/PWは、実際に生産・選抜した個体で別評価してください。</div></div>`}
function installSimulator(){const sec=$('#rebuild');if(!sec||$('#nitroSimulator'))return;const card=document.createElement('div');card.className='card';card.id='nitroSimulator';card.hidden=true;card.setAttribute('aria-hidden','true');card.innerHTML=`<h3 class="section-title">2～3世代 最終ニトロ計算</h3><p class="muted">共通配合エンジンで各世代の15祖先からSP/ST/PWニトロを再計算します。途中世代のニトロを足し算しません。</p><div class="field"><label>起点繁殖牝馬</label><select id="nitroStart"></select></div><div class="nitro-stage"><label>1代目 種牡馬</label><select id="nitroSire1"></select><div id="nitroResult1"></div></div><div class="nitro-stage"><label>2代目 種牡馬</label><select id="nitroSire2"></select><div id="nitroResult2"></div></div><div class="nitro-stage"><label>3代目／締め 種牡馬</label><select id="nitroSire3"></select><div id="nitroResult3"></div></div><div class="notice"><b>判定基準：</b>最終世代のニトロ＋母自身の繁殖能力＋父の実績/底力/安定/距離＋配合理論を合わせて判断します。</div>`;const intro=sec.querySelector('.card');intro?.insertAdjacentElement('afterend',card);const starts=sourceMares(),start=$('#nitroStart');start.innerHTML=starts.map(x=>`<option value="${esc(x.value)}">${esc(x.name)}</option>`).join('');const current=$('#rebuildStarter')?.value||db.rebuildStudy?.starter||'',mv='m:'+current;if(starts.some(x=>x.value===mv))start.value=mv;const goal=$('#rebuildGoal')?.value||'arc',def=routeDefault(resolveMare(start.value)?.name||current,goal);$('#nitroSire1').innerHTML=sireOptions(def?'m:'+def:'',true);if(def)$('#nitroSire1').value='m:'+def;$('#nitroSire2').innerHTML=sireOptions('',true);$('#nitroSire3').innerHTML=sireOptions('',true);[start,$('#nitroSire1'),$('#nitroSire2'),$('#nitroSire3')].forEach(x=>x.onchange=renderSimulator);$('#rebuildGoal')?.addEventListener('change',()=>setTimeout(syncSimulator,20));$('#rebuildStarter')?.addEventListener('change',()=>setTimeout(syncSimulator,20));renderSimulator()}
function syncSimulator(){const start=$('#nitroStart');if(!start)return;const n=$('#rebuildStarter')?.value,mv='m:'+n;if([...start.options].some(o=>o.value===mv))start.value=mv;const def=routeDefault(n,$('#rebuildGoal')?.value||'arc');if(def)$('#nitroSire1').value='m:'+def;$('#nitroSire2').value='';$('#nitroSire3').value='';renderSimulator()}
function renderSimulator(){const m=resolveMare($('#nitroStart')?.value);if(!m)return;let ma=m.ancestor,active=true;for(let i=1;i<=3;i++){const sel=$('#nitroSire'+i),holder=$('#nitroResult'+i);if(!holder)continue;if(!active){holder.outerHTML=stageHtml(i,null,null);continue}const s=resolveSire(sel?.value);if(!s){holder.outerHTML=stageHtml(i,null,null);active=false;continue}const n=calcAncestors(s.ancestor,ma);holder.outerHTML=stageHtml(i,s,n);ma=deriveChild(s.name,s.ancestor,ma);if(!ma)active=false}}
function expose(){window.DABISTA_NITRO_ENGINE={version:2,source:'common-breeding-engine',calcAncestors,deriveChildAncestor:deriveChild,calcPairByName:(sireName,mareName)=>{const s=master(sireName),m=master(mareName);return s&&m?calcAncestors(s.ancestor,m.ancestor):null},calcPairForHorse:(sireName,horseId)=>{const s=master(sireName),h=db.horses.find(x=>x.id===horseId),a=horseAnc(h);return s&&a?calcAncestors(s.ancestor,a):null}}}
async function json(path){const u=new URL(path,location.href);u.searchParams.set('_',BUILD);const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(path+' HTTP '+r.status);return r.json()}
async function load(){addStyles();try{engine=await window.DABISTA_BREEDING_ENGINE.ready;const [s,r]=await Promise.all([json('data/stallions.json'),json('data/rebuild-research.json')]);stallions=s.stallions||[];research=r;expose();installFilter();decorateBreed();installSimulator();if(!window.DABISTA_BREED_PAIR_INDEX){$('#breedMare')?.addEventListener('change',()=>setTimeout(decorateBreed,160));$('#stallionSearch')?.addEventListener('input',()=>setTimeout(decorateBreed,160));$('#breedGoal')?.addEventListener('change',()=>setTimeout(decorateBreed,160));const target=$('#breedCandidates');if(target)new MutationObserver(()=>setTimeout(decorateBreed,0)).observe(target,{childList:true})}}catch(e){window.APP_ERRORS?.push({at:new Date().toISOString(),message:'nitro-engine: '+String(e)});const st=$('#rebuildStatus');if(st)st.textContent='共通配合エンジンの読み込みに失敗しました。更新確認を試してください。'}}
function newer(a,b){const A=String(a).split('.').map(Number),B=String(b).split('.').map(Number);for(let i=0;i<3;i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return false}
async function checkUpdate(show=false){try{const u=new URL('version.json',location.href);u.searchParams.set('_',Date.now());const r=await fetch(u,{cache:'no-store'}),v=await r.json();if(newer(v.version,V)||v.build!==BUILD){$('#updateText').textContent=`最新版 v${v.version} / ${v.build} があります`;$('#updatebar').classList.add('show')}else{$('#updatebar').classList.remove('show');if(show)alert(`最新版です\nv${V} / ${BUILD}`)}}catch{if(show)alert('更新確認に失敗しました。')}}
setTimeout(load,1550);setTimeout(()=>{if($('#refreshBtn'))$('#refreshBtn').onclick=()=>checkUpdate(true);checkUpdate(false)},4800);
})();
